SELECT board.TITLE, board.BOARD_ID, reply.REPLY_ID, reply.WRITER_ID, reply.CONTENTS, DATE_FORMAT(reply.CREATED_DATE,"%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_REPLY as reply
     INNER JOIN
     ( SELECT * FROM USED_GOODS_BOARD
       WHERE CREATED_DATE >= "2022-10-01" and CREATED_DATE < "2022-11-01" ) as board
     ON reply.BOARD_ID=board.BOARD_ID
ORDER BY reply.CREATED_DATE, board.TITLE