SELECT concat("/home/grep/src/", file.BOARD_ID, "/", file.FILE_ID, file.FILE_NAME, file.FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE as file INNER JOIN USED_GOODS_BOARD as board ON file.BOARD_ID=board.BOARD_ID
WHERE board.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID desc